name: Run External Script on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-external-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: gdiazvillegas/gddy_coriander_secu_hackathon_2024
          path: coriander
          ref: main
          token: ${{secrets.CORIANDER_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r coriander/requirements.txt
          
      - name: Run external script with PR diff
        run: |
          python coriander/CoreApp/codeDiff.py ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}}

      - name: Run promptWithToken script
        run: python coriander/CoreApp/promptWithToken.py
